spring:
  flyway:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  application:
    name: userService
logging:
  level:
    com:
      userservice: DEBUG
  file:
    name: application.logx
security:
  app:
    jwtSecret: SimpleLongPhraseForSecretJwtTokenSimpleLongPhraseForSecretJwtTokenSimpleLongPhraseForSecretJwtToken
    jwtExpirationMs: 84600000
